/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.core.CandidatoDAO;
import factory.DAOListener;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Candidato;
import util.Data;

/**
 *
 * @author Link
 */
public class TelaRegistro extends javax.swing.JFrame {

    private boolean isEditando;
    private Integer ultimoIdPego;

    private void rederizaTabela() {
       String[] columnNames = {"ID", "Nome", "Telefone", "Cidade", "Pretensão salarial"};
        DefaultTableModel tabela = new DefaultTableModel(columnNames, 0);
    CandidatoDAO candidatoDAO = DAOListener.getDAOFactory().getCadidatoDao();

        List<Candidato> dao = candidatoDAO.listAll();
        for (Candidato model : dao) {
            Object[] data = {model.getId(), model.getNumero(), 
               model.getTelefone(), model.getCidade(), model.getPretensaoSalarial()
,              };
           tabela.addRow(data);
        }
        tabelaPrincipal.setModel(tabela);
    }

    /**
     * Creates new form TelaRegistro
     */
    public TelaRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        Lista3 = new javax.swing.JPanel();
        btnAdicionar1 = new javax.swing.JButton();
        btnRemover1 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabelaPrincipal = new javax.swing.JTable();
        btnAlterar = new javax.swing.JButton();
        Lista1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        fieldNome = new javax.swing.JTextField();
        fieldCEP = new javax.swing.JTextField();
        fieldUF = new javax.swing.JTextField();
        fieldCPF = new javax.swing.JTextField();
        fieldEndereco = new javax.swing.JTextField();
        fieldBairro = new javax.swing.JTextField();
        radioMasculino = new javax.swing.JRadioButton();
        radioFeminino = new javax.swing.JRadioButton();
        fieldTelefone = new javax.swing.JTextField();
        fieldCidade = new javax.swing.JTextField();
        fieldDataDeNascimento = new javax.swing.JTextField();
        btnAvancar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        fieldObservacoes = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        fieldEmail = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        fieldRG = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        fieldNacionalidade = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        fieldNumero = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        fieldComplemento = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        fieldPretencao = new javax.swing.JTextField();
        fieldEstadoCivil = new javax.swing.JComboBox<>();
        Lista2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        fieldNomeCurso = new javax.swing.JTextField();
        btnAvancar1 = new javax.swing.JButton();
        btnCancelar1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        fieldDescricaoCurso = new javax.swing.JTextArea();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        boxFormacao = new javax.swing.JComboBox<>();
        boxFase = new javax.swing.JComboBox<>();
        boxSituacao = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        fieldNomeEmpresa = new javax.swing.JTextField();
        fieldDataAdmissao = new javax.swing.JTextField();
        fieldCargo = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        fieldObservacaoEmpresa = new javax.swing.JTextArea();
        btnAdd = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        fieldDataDemissao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        mainPanel.setLayout(new java.awt.CardLayout());

        Lista3.setBackground(new java.awt.Color(254, 254, 254));
        Lista3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Lista3.setToolTipText("");
        Lista3.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        Lista3.setInheritsPopupMenu(true);

        btnAdicionar1.setText("Adicionar");
        btnAdicionar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAdicionar1.setContentAreaFilled(false);
        btnAdicionar1.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnAdicionar1.setDefaultCapable(false);
        btnAdicionar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionar1ActionPerformed(evt);
            }
        });

        btnRemover1.setText("Remover");
        btnRemover1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRemover1.setContentAreaFilled(false);
        btnRemover1.setCursor(new java.awt.Cursor(java.awt.Cursor.E_RESIZE_CURSOR));
        btnRemover1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemover1ActionPerformed(evt);
            }
        });

        tabelaPrincipal.setBackground(new java.awt.Color(254, 254, 254));
        tabelaPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabelaPrincipal.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        tabelaPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Telefone", "Cidade", "Pretenção Salarial"
            }
        ));
        tabelaPrincipal.setFillsViewportHeight(true);
        tabelaPrincipal.setGridColor(new java.awt.Color(254, 254, 254));
        tabelaPrincipal.setNextFocusableComponent(btnAdicionar1);
        tabelaPrincipal.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane6.setViewportView(tabelaPrincipal);

        btnAlterar.setText("Alterar");
        btnAlterar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAlterar.setContentAreaFilled(false);
        btnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.E_RESIZE_CURSOR));
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Lista3Layout = new javax.swing.GroupLayout(Lista3);
        Lista3.setLayout(Lista3Layout);
        Lista3Layout.setHorizontalGroup(
            Lista3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Lista3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Lista3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRemover1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdicionar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Lista3Layout.setVerticalGroup(
            Lista3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Lista3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnAdicionar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemover1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
            .addGroup(Lista3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        mainPanel.add(Lista3, "card1");

        Lista1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Lista1.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        Lista1.setInheritsPopupMenu(true);
        Lista1.setPreferredSize(new java.awt.Dimension(800, 346));

        jLabel1.setText("Nome");

        jLabel2.setText("CPF");

        jLabel3.setText("Telefone");

        jLabel4.setText("CEP");

        jLabel5.setText("Endereço");

        jLabel6.setText("Cidade");

        jLabel7.setText("UF");

        jLabel8.setText("Bairro");

        jLabel9.setText("Data de nascimento");

        jLabel10.setText("Sexo");

        jLabel15.setText("Observações");

        fieldNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNomeActionPerformed(evt);
            }
        });

        fieldCEP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fieldUF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fieldCPF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fieldEndereco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fieldEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEnderecoActionPerformed(evt);
            }
        });

        fieldBairro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fieldBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldBairroActionPerformed(evt);
            }
        });

        radioMasculino.setText("Masculino");
        radioMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMasculinoActionPerformed(evt);
            }
        });

        radioFeminino.setText("Feminino");

        fieldTelefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fieldCidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fieldDataDeNascimento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnAvancar.setBackground(new java.awt.Color(255, 255, 255));
        btnAvancar.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        btnAvancar.setText("Avançar");
        btnAvancar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAvancar.setContentAreaFilled(false);
        btnAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        fieldObservacoes.setColumns(20);
        fieldObservacoes.setRows(5);
        jScrollPane2.setViewportView(fieldObservacoes);

        jLabel19.setText("E-mail");

        fieldEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel20.setText("RG");

        fieldRG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fieldRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldRGActionPerformed(evt);
            }
        });

        jLabel21.setText("Estado civil");

        jLabel22.setText("Nacionalidade");

        fieldNacionalidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel23.setText("Nº");

        fieldNumero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel24.setText("Complemento");

        fieldComplemento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fieldComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldComplementoActionPerformed(evt);
            }
        });

        jLabel26.setText("Pretenção salarial");

        fieldPretencao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        fieldEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro", "Divorciado", "Casado" }));
        fieldEstadoCivil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fieldEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEstadoCivilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Lista1Layout = new javax.swing.GroupLayout(Lista1);
        Lista1.setLayout(Lista1Layout);
        Lista1Layout.setHorizontalGroup(
            Lista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Lista1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Lista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Lista1Layout.createSequentialGroup()
                        .addGroup(Lista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Lista1Layout.createSequentialGroup()
                                .addGroup(Lista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Lista1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)
                                        .addComponent(radioMasculino)
                                        .addGap(18, 18, 18)
                                        .addComponent(radioFeminino))
                                    .addGroup(Lista1Layout.createSequentialGroup()
                                        .addGroup(Lista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(Lista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fieldNome, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(fieldEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(fieldNacionalidade)
                                            .addComponent(fieldCEP)
                                            .addComponent(fieldUF))))
                                .addGap(16, 16, 16)
                                .addGroup(Lista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Lista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(Lista1Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(33, 33, 33))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Lista1Layout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addGroup(Lista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel20)
                                                .addComponent(jLabel2))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(Lista1Layout.createSequentialGroup()
                                        .addGroup(Lista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel23)
                                            .addGroup(Lista1Layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(jLabel8)))
                                        .addGap(82, 82, 82)))
                                .addGroup(Lista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(fieldNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                    .addComponent(fieldBairro, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldEndereco, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldCPF, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldRG, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Lista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel26))
                                .addGap(18, 18, 18)
                                .addGroup(Lista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(fieldCidade, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldDataDeNascimento, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                    .addComponent(fieldComplemento, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                    .addComponent(fieldPretencao)
                                    .addComponent(fieldEstadoCivil, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel15))
                        .addGap(93, 93, 93))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Lista1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAvancar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        Lista1Layout.setVerticalGroup(
            Lista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Lista1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Lista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(fieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Lista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(fieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(fieldEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(Lista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(fieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(Lista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Lista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fieldNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22)
                        .addComponent(jLabel23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Lista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24)
                        .addComponent(fieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Lista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fieldUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(fieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(fieldDataDeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(Lista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(radioMasculino)
                    .addComponent(radioFeminino)
                    .addComponent(jLabel26)
                    .addComponent(fieldPretencao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Lista1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAvancar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mainPanel.add(Lista1, "card2");

        Lista2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Lista2.setFont(new java.awt.Font("DejaVu Sans", 0, 15)); // NOI18N
        Lista2.setInheritsPopupMenu(true);
        Lista2.setPreferredSize(new java.awt.Dimension(800, 346));

        jLabel12.setText("Formação escolar");

        jLabel13.setText("Nome do curso");

        jLabel30.setText("Descrição do curso");

        fieldNomeCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNomeCursoActionPerformed(evt);
            }
        });

        btnAvancar1.setBackground(new java.awt.Color(255, 255, 255));
        btnAvancar1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAvancar1.setText("Avançar");
        btnAvancar1.setBorder(null);
        btnAvancar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvancar1ActionPerformed(evt);
            }
        });

        btnCancelar1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCancelar1.setText("Cancelar");
        btnCancelar1.setBorder(null);
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });

        fieldDescricaoCurso.setColumns(20);
        fieldDescricaoCurso.setRows(5);
        jScrollPane3.setViewportView(fieldDescricaoCurso);

        jLabel31.setText("Fase escolar");

        jLabel32.setText("Situação");

        boxFormacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecione --", "Ensino fundamental", "Ensino Médio", "Graduação", "Pós-Graduação", "Mestrado", "Doutorado" }));
        boxFormacao.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                boxFormacaoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        boxFormacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxFormacaoActionPerformed(evt);
            }
        });

        boxFase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecione--", "Incompleto", "Cursando", "Completo" }));

        boxSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecione--", "Incompleto", "Cursando", "Completo" }));

        jLabel14.setText("Nome da empresa");

        jLabel16.setText("Data admissão");

        jLabel17.setText("Cargo");

        jLabel18.setText("Observação");

        fieldObservacaoEmpresa.setColumns(20);
        fieldObservacaoEmpresa.setRows(5);
        jScrollPane4.setViewportView(fieldObservacaoEmpresa);

        btnAdd.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAdd.setText("Adicionar");
        btnAdd.setBorder(null);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel25.setText("As caixas de texto em branco não serão salvos");

        jLabel27.setText("Data demissão");

        javax.swing.GroupLayout Lista2Layout = new javax.swing.GroupLayout(Lista2);
        Lista2.setLayout(Lista2Layout);
        Lista2Layout.setHorizontalGroup(
            Lista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Lista2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Lista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Lista2Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAvancar1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(Lista2Layout.createSequentialGroup()
                        .addGroup(Lista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Lista2Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE))
                            .addGroup(Lista2Layout.createSequentialGroup()
                                .addGroup(Lista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addGroup(Lista2Layout.createSequentialGroup()
                                        .addGroup(Lista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel31)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel32))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(Lista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(boxFormacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(fieldNomeCurso)
                                            .addComponent(boxFase, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(boxSituacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(153, 153, 153)
                                .addGroup(Lista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addGroup(Lista2Layout.createSequentialGroup()
                                        .addGroup(Lista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel27))
                                        .addGap(18, 18, 18)
                                        .addGroup(Lista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(fieldNomeEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                            .addComponent(fieldDataAdmissao)
                                            .addComponent(fieldCargo)
                                            .addComponent(fieldDataDemissao))))))
                        .addContainerGap())))
        );
        Lista2Layout.setVerticalGroup(
            Lista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Lista2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Lista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(boxFormacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(fieldNomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Lista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(boxFase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldDataAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(6, 6, 6)
                .addGroup(Lista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(fieldNomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(fieldDataDemissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(Lista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(boxSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(fieldCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(Lista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(Lista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Lista2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Lista2Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addGroup(Lista2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAvancar1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addContainerGap())))
        );

        mainPanel.add(Lista2, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mainPanel.getAccessibleContext().setAccessibleName("");
        mainPanel.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioMasculinoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        CardLayout manager = (CardLayout) mainPanel.getLayout();
        manager.show(mainPanel, "card1");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void fieldEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEnderecoActionPerformed

    private void fieldRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldRGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldRGActionPerformed

    private void fieldComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldComplementoActionPerformed

    private void btnAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancarActionPerformed

        //Array de campos
        Map<String, String> aCampo = new HashMap<String, String>();

        aCampo.put("nome", fieldNome.getText());
        aCampo.put("cpf", fieldCPF.getText());
        aCampo.put("sexo", radioMasculino.isSelected() ? "Masculino" : radioFeminino.isSelected() ?  "Feminino" : null);
        aCampo.put("email", fieldEmail.getText());
        aCampo.put("telefone", fieldTelefone.getText());
        aCampo.put("dataNascimento", fieldDataDeNascimento.getText());
        aCampo.put("rg", fieldRG.getText());
        aCampo.put("estadoCivil", String.valueOf(fieldEstadoCivil.getSelectedItem()));
        aCampo.put("nacionalidade", fieldNacionalidade.getText());
        aCampo.put("cep", fieldCEP.getText());
        aCampo.put("endereco", fieldEndereco.getText());
        aCampo.put("numero", fieldNumero.getText());
        aCampo.put("bairro", fieldBairro.getText());
        aCampo.put("complemento", fieldComplemento.getText());
        aCampo.put("cidade", fieldCidade.getText());
        aCampo.put("uf", fieldUF.getText());
        aCampo.put("pretensaoSalarial", fieldPretencao.getText());

        //Verifica campos nulos
        if (verificaCampoCandidado((HashMap<String, String>) aCampo))
        {
            // JOptionPane.showMessageDialog(null, "Preencha os campos obrigatórios!");
            //  return;
        }

        controller.TelaRegistro telaRegistro = new controller.TelaRegistro();

       // telaRegistro.gravaCandidato((HashMap<String, String>) aCampo);

        CardLayout manager = (CardLayout) mainPanel.getLayout();
        manager.show(mainPanel, "card3");
    }//GEN-LAST:event_btnAvancarActionPerformed

    private void fieldBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldBairroActionPerformed

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        CardLayout manager = (CardLayout) mainPanel.getLayout();
        manager.show(mainPanel, "card1");
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    private void btnAvancar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvancar1ActionPerformed

        String nome = fieldNome.getText();
        String cidade = fieldCidade.getText();
        String telefone = fieldTelefone.getText();
        String pretencao = fieldPretencao.getText();


        DefaultTableModel val = (DefaultTableModel) tabelaPrincipal.getModel();
            val.addRow(new String[] {nome, cidade, telefone, pretencao});

        fieldEmail.setText("");
        fieldRG.setText("");
        float CENTER_ALIGNMENT1 = fieldEmail.CENTER_ALIGNMENT;

        fieldEmail.requestFocus();
        CardLayout manager = (CardLayout) mainPanel.getLayout();
        manager.show(mainPanel, "card1");
    }//GEN-LAST:event_btnAvancar1ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void fieldNomeCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNomeCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNomeCursoActionPerformed

    private void boxFormacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxFormacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxFormacaoActionPerformed

    private void boxFormacaoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_boxFormacaoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_boxFormacaoAncestorAdded
private Integer getSelectedId() {
        if (tabelaPrincipal.getSelectedRow() == -1) {
            return null;
        }

        Object valor = tabelaPrincipal.getModel().getValueAt(
                tabelaPrincipal.getSelectedRow(), 0);
        return (Integer) valor;
    }
    private void fieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNomeActionPerformed

    private void fieldEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEstadoCivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEstadoCivilActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       rederizaTabela();
    }//GEN-LAST:event_formWindowActivated

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        CandidatoDAO candidatoDAO = DAOListener.getDAOFactory().getCadidatoDao();
        Candidato cand = candidatoDAO.listByKey(getSelectedId());
        ultimoIdPego = getSelectedId();
        isEditando = true;
        alteraCandidato(cand);
        CardLayout manager = (CardLayout) mainPanel.getLayout();
        
        manager.show(mainPanel, "card2");
    }//GEN-LAST:event_btnAlterarActionPerformed
private void alteraCandidato(Candidato cand) {
    fieldBairro.setText(((cand.getBairro() == null) ? "" : cand.getBairro()));
    fieldCEP.setText(((cand.getCep() == null) ? "" : cand.getCep()));
    fieldCPF.setText(((cand.getCpf() == null) ? "" : cand.getCpf()));   
    fieldCidade.setText(((cand.getCidade() == null) ? "" : cand.getCidade()));     
    fieldDataAdmissao.setText(((Data.dateExibe(cand.getDataNascimento()) == null) ? "" : Data.dateExibe(cand.getDataNascimento())));    //fieldDataDeNascimento.setText(((Data.dateExibe(cand.getDataNascimento()) == null) ? "" : cand.get));
    //fieldDataDemissao.setText(((cand.get == null) ? "" : cand.get));     
    fieldEmail.setText(((cand.getEmail() == null) ? "" : cand.getEmail()));
    fieldEndereco.setText(((cand.getEndereco() == null) ? "" : cand.getEndereco()));     
    fieldNacionalidade.setText(((cand.getNacionalidade() == null) ? "" : cand.getNacionalidade()));
    fieldNome.setText(((cand.getNome() == null) ? "" : cand.getNome()));
    //fieldNomeCurso.setText(((cand.ge == null) ? "" : cand.get));
   // fieldNomeEmpresa.setText(((cand.get == null) ? "" : cand.get));
    fieldNumero.setText(((cand.getNumero() == null) ? "" : cand.getNumero()));
     
    fieldPretencao.setText(((cand.getPretensaoSalarial().toString() == null) ? "" : cand.getPretensaoSalarial().toString()));
    fieldRG.setText(((cand.getRg() == null) ? "" : cand.getRg()));
    fieldTelefone.setText(((cand.getTelefone() == null) ? "" : cand.getTelefone()));
    fieldUF.setText(((cand.getUf() == null) ? "" : cand.getUf()));
      
    }
    private void btnRemover1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemover1ActionPerformed

        CandidatoDAO candidatoDAO = DAOListener.getDAOFactory().getCadidatoDao();
        if (getSelectedId() != null) {
            int resp = JOptionPane.showConfirmDialog(this, "Deseja realmente excluir o registro???");
            if (resp == JOptionPane.YES_OPTION)
            candidatoDAO.delete(getSelectedId());
        }
    }//GEN-LAST:event_btnRemover1ActionPerformed

    private void btnAdicionar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionar1ActionPerformed

        CardLayout manager = (CardLayout) mainPanel.getLayout();
        manager.show(mainPanel, "card2");
    }//GEN-LAST:event_btnAdicionar1ActionPerformed

    private boolean verificaCampoCandidado(HashMap<String, String> aCampo)
    {
        /*
        //Campos obrigatorios
        for (Map.Entry<String, String> entry : aCampo.entrySet())
        {

            String campoNome  = entry.getKey().toString();
            String campoValor   = entry.getValue().toString();

            //Campos obrigatorios
            if (campoNome.equals("nome") || campoNome.equals("cpf") || campoNome.equals("email") || campoNome.equals("cidade") || campoNome.equals("pretensaoSalarial"))
            {
                    return campoValor.isEmpty();
            }

        }
        */
        return true;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRegistro().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Lista1;
    private javax.swing.JPanel Lista2;
    private javax.swing.JPanel Lista3;
    private javax.swing.JComboBox<String> boxFase;
    private javax.swing.JComboBox<String> boxFormacao;
    private javax.swing.JComboBox<String> boxSituacao;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAdicionar1;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAvancar;
    private javax.swing.JButton btnAvancar1;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnRemover1;
    private javax.swing.JTextField fieldBairro;
    private javax.swing.JTextField fieldCEP;
    private javax.swing.JTextField fieldCPF;
    private javax.swing.JTextField fieldCargo;
    private javax.swing.JTextField fieldCidade;
    private javax.swing.JTextField fieldComplemento;
    private javax.swing.JTextField fieldDataAdmissao;
    private javax.swing.JTextField fieldDataDeNascimento;
    private javax.swing.JTextField fieldDataDemissao;
    private javax.swing.JTextArea fieldDescricaoCurso;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldEndereco;
    private javax.swing.JComboBox<String> fieldEstadoCivil;
    private javax.swing.JTextField fieldNacionalidade;
    private javax.swing.JTextField fieldNome;
    private javax.swing.JTextField fieldNomeCurso;
    private javax.swing.JTextField fieldNomeEmpresa;
    private javax.swing.JTextField fieldNumero;
    private javax.swing.JTextArea fieldObservacaoEmpresa;
    private javax.swing.JTextArea fieldObservacoes;
    private javax.swing.JTextField fieldPretencao;
    private javax.swing.JTextField fieldRG;
    private javax.swing.JTextField fieldTelefone;
    private javax.swing.JTextField fieldUF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton radioFeminino;
    private javax.swing.JRadioButton radioMasculino;
    private javax.swing.JTable tabelaPrincipal;
    // End of variables declaration//GEN-END:variables
}
